import type { CSSProperties } from 'react';
import {
  Archive,
  ArrowDown,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Braces,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CloudUpload,
  Code,
  Compass,
  Copy,
  Database,
  Disc,
  Download,
  Eye,
  File,
  FileMusic,
  FileText,
  FileUp,
  Film,
  Folder,
  FolderInput,
  FolderOpen,
  FolderPen,
  FolderPlus,
  Gauge,
  Globe,
  HardDrive,
  Image,
  Info,
  LayoutGrid,
  List,
  ListChecks,
  ListFilter,
  ListX,
  Move,
  Network,
  Newspaper,
  NotebookPen,
  OctagonX,
  Pencil,
  Percent,
  Plus,
  Presentation,
  RefreshCw,
  Save,
  Search,
  SearchX,
  Settings,
  Table,
  Trash,
  TriangleAlert,
  Undo2,
  Upload,
  User,
  WifiOff,
  X,
  FileQuestionMark,
  type LucideIcon,
} from 'lucide-react';

/** Maps legacy Material Symbol names (incl. getFileIcon outputs) to Lucide. */
const MAP: Record<string, LucideIcon> = {
  add: Plus,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  keyboard_arrow_up: ChevronUp,
  keyboard_arrow_down: ChevronDown,
  expand_more: ChevronDown,
  chevron_right: ChevronRight,
  check: Check,
  check_circle: CircleCheck,
  close: X,
  error: OctagonX,
  error_outline: CircleAlert,
  info: Info,
  warning: TriangleAlert,
  search: Search,
  search_off: SearchX,
  explore: Compass,
  folder: Folder,
  folder_open: FolderOpen,
  folder_zip: Archive,
  create_new_folder: FolderPlus,
  upload: Upload,
  upload_file: FileUp,
  cloud_upload: CloudUpload,
  download: Download,
  drive_file_move: FolderInput,
  drive_file_rename_outline: FolderPen,
  edit: Pencil,
  edit_note: NotebookPen,
  content_copy: Copy,
  save: Save,
  delete: Trash,
  delete_forever: Trash,
  delete_sweep: Trash,
  restore: Undo2,
  clear_all: ListX,
  database: Database,
  storage: HardDrive,
  dns: Network,
  person: User,
  visibility: Eye,
  grid_view: LayoutGrid,
  view_list: List,
  sync_alt: ArrowLeftRight,
  refresh: RefreshCw,
  filter_alt: ListFilter,
  settings: Settings,
  wifi_off: WifiOff,
  checklist: ListChecks,
  http: Globe,
  speed: Gauge,
  percent: Percent,
  image: Image,
  movie: Film,
  audio_file: FileMusic,
  picture_as_pdf: FileText,
  code: Code,
  data_object: Braces,
  description: FileText,
  article: Newspaper,
  table_chart: Table,
  slideshow: Presentation,
  disc_full: Disc,
  draft: File,
  move: Move,
};

interface IconProps {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
  style?: CSSProperties;
}

export function Icon({ name, size = 18, className, strokeWidth = 2, style }: IconProps) {
  const C = MAP[name] ?? FileQuestionMark;
  return <C size={size} className={className} strokeWidth={strokeWidth} style={style} aria-hidden />;
}
